[metadata]
name = mahmoud
version = 0.1.0
author = Mahmoud
description = A Python package by Mahmoud
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ghareebmahmoud61-del/mahmoud
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.6
install_requires =

[options.packages.find]
where = .
include = mahmoud*
